" change the default character when no match found
let g:WebDevIconsUnicodeDecorateFileNodesDefaultSymbol = '󰈔'
" add or override individual additional file types
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {} " needed
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['v'] = '󰻟'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['sv'] = '󰻠'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['m'] = '󰯃'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['tcl'] = '󰯃'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['do'] = '󰯃'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['gitignore'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['md'] = '󰍔'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['txt'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['log'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['bin'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['bit'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['doc'] = '󱎒'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['docx'] = '󱎒'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['xls'] = '󱎏'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['xlsx'] = '󱎏'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['ppt'] = '󱎐'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['pptx'] = '󱎐'
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['zip'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['7c'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['tar'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['dll'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['exe'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['snippets'] = ''

